# Generated by Django 3.2.7 on 2021-10-03 20:47

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('x_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x_test', to='flows.dataframe')),
                ('x_train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x_train', to='flows.dataframe')),
                ('y_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='y_test', to='flows.dataframe')),
                ('y_train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='y_train', to='flows.dataframe')),
            ],
        ),
    ]
