# Generated by Django 3.2.7 on 2021-10-05 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='x_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x_test', to='flows.dataframe', unique=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='x_train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x_train', to='flows.dataframe', unique=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='y_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='y_test', to='flows.dataframe', unique=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='y_train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='y_train', to='flows.dataframe', unique=True),
        ),
    ]
