# Generated by Django 3.2.7 on 2021-10-31 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flows', '0006_auto_20211017_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train', to='flows.dataframe'),
        ),
        migrations.CreateModel(
            name='PrepareData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cols', picklefield.fields.PickledObjectField(editable=False)),
                ('colFilter', models.IntegerField(blank=True, null=True)),
                ('constraints', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepareData', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flow',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_query', to='flows.preparedata'),
        ),
    ]
