# Generated by Django 3.2.7 on 2021-11-03 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flows.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flows', '0008_auto_20211103_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloftrain',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelOfTrain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modeloftrain',
            name='upload',
            field=models.FileField(upload_to=flows.models.user_directory_path),
        ),
    ]
