# Generated by Django 3.2.7 on 2021-11-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0009_auto_20211103_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloftrain',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
