# Generated by Django 3.2.7 on 2021-12-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0011_auto_20211206_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
