# Generated by Django 3.2.7 on 2021-12-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0013_alter_flow_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flow',
            unique_together=set(),
        ),
    ]
