# Generated by Django 3.2.7 on 2021-12-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0014_alter_flow_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(fields=('title', 'owner'), name='unique title'),
        ),
    ]
