# Generated by Django 3.2.7 on 2021-12-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0015_flow_unique title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flow',
            name='unique title',
        ),
    ]
