# Generated by Django 3.2.7 on 2022-05-02 16:17

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0016_remove_flow_unique title'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelresult',
            name='hyperparameters',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
            preserve_default=False,
        ),
    ]
