# Generated by Django 3.2.7 on 2022-05-02 16:23

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0017_modelresult_hyperparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelresult',
            name='hyperparameters',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
