# Generated by Django 3.2.7 on 2022-05-17 21:14

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0019_flow_datatest'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedata',
            name='categories',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparedata',
            name='nans',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparedata',
            name='normalize',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
            preserve_default=False,
        ),
    ]
