# Generated by Django 3.2.7 on 2022-05-18 10:24

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0020_auto_20220517_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedata',
            name='sliceStr',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
            preserve_default=False,
        ),
    ]
