# Generated by Django 3.2.7 on 2022-05-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0021_preparedata_slicestr'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='avgLoss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='loss_fn',
            field=models.CharField(default='SGD', max_length=100),
            preserve_default=False,
        ),
    ]
