# Generated by Django 3.2.7 on 2022-05-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0022_auto_20220521_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='score',
        ),
    ]
